import Head from "next/head";

import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

import Navbar from "./Navbar";
import Footer from "./Footer";
import { useStateContext } from "@/context/StateContext";

export default function Layout({ children }) {
  const { footerContext, setFooterContext } = useStateContext();

  return (
    <div className={`${inter.className} layout`}>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main className="main-container">{children}</main>

      <footer>
        {footerContext &&
          footerContext.map((footer) => {
            return <Footer footer={footer} />;
          })}
      </footer>
    </div>
  );
}
